### ISSUE TITLE
Gitlab actions support

### ISSUE THREAD

**Issue by dimateos** [actionforge/vscode-ext#30]
I use them less frequently, but would love a visual node graph editor for them too :)

Are they still a planned feature?

Best regards!

**Comment by sebastianrath** [comment]
Hi, you can download the cli tool [here](https://actionforge.dev/download) and run the graph manually from your GitLab action.

`actrun.exe my-graph.yml`

Does this help?

**Comment by dimateos** [comment]
Not really :(

I tried running the gitlab yml attached at the bottom (and a github one too) and the only output I get is the **help**.
So there is _not even an error_., I tried:
* actrun.exe my-graph.yml
* actrun.exe completion my-graph.yml
* actrun.exe "my-graph.yml"
* actrun.exe completion "my-graph.yml"
* ... also adding ./ or .\\

```
# version:
D:\Archivos\Downloads\actrun-v0.9.140.cli-x64-windows>actrun.exe version
actrun version vv0.9.140 (prod, windows amd64, 2024-11-05T13:32:36Z, 6310a4aa)
```

The readme links to https://docs.actionforge.dev/first-steps/ which only mentions .act execution so mention of .yml

Btw the help says:
* Use "actrun [command] --help" for more information about a command.
* But `actrun.exe completion --help` yields no extra info, just the regular help. Only help has help XD

```yml
image: fedora:rawhide

stages:
  - build

before_script:
  - dnf -y upgrade --disablerepo=rawhide-modular --nogpgcheck fedora-repos fedora-repos-rawhide
  - dnf -y upgrade --disablerepo=rawhide-modular
  - dnf -y install --disablerepo=rawhide-modular @buildsys-build autoconf automake libtool gettext gettext-devel gperf expat-devel freetype-devel libuuid-devel json-c-devel git docbook-utils docbook-utils-pdf

shared-build:
  stage: build
  script:
    - export BUILD_ID="fontconfig-$CI_JOB_NAME_$CI_COMMIT_SHA-$CI_JOB_ID"
    - export PREFIX="$(pwd)/prefix-$BUILD_ID"
    - export BUILDDIR="$(pwd)/build-$BUILD_ID"
    - export MAKEFLAGS="-j4"
    - mkdir "$BUILDDIR" "$PREFIX"
    - cd "$BUILDDIR"
    - ../autogen.sh --prefix="$PREFIX" --enable-shared --disable-static
    - make
    - make check
    - make install
    - make distcheck
  artifacts:
    name: fontconfig-$CI_COMMIT_SHA-$CI_JOB_ID
    when: always
    paths:
      - build-*/fontconfig-*.tar.bz2
      - build-*/fontconfig*/_build/sub/*.log
      - build-*/fontconfig*/_build/sub/test/*.log
      - build-*/fontconfig*/_build/sub/test/*.trs
      - build-*/*.log
      - prefix-*
static-build:
  stage: build
  script:
    - export BUILD_ID="fontconfig-$CI_JOB_NAME_$CI_COMMIT_SHA-$CI_JOB_ID"
    - export PREFIX="$(pwd)/prefix-$BUILD_ID"
    - export BUILDDIR="$(pwd)/build-$BUILD_ID"
    - export MAKEFLAGS="-j4"
    - mkdir "$BUILDDIR"
    - cd "$BUILDDIR"
    - ../autogen.sh --prefix="$PREFIX" --disable-shared --enable-static
    - make
    - make check
  artifacts:
    name: fontconfig-$CI_COMMIT_SHA-$CI_JOB_ID
    when: always
    paths:
      - build-*/*.log
      - build-*/test/*.log
      - build-*/test/*.trs
```
